### ISSUE TITLE
Compare with AMP

### ISSUE THREAD

**Issue by xizaoqu** [yz-cnsdqz/GAMMA-release#2]
Hi, thanks for sharing your work. 
I'm not sure if the pipeline in your work is better than AMP (Adversarial motion priors) to generate wandering humanoids. In your video, it says that your method is better in diversity and generalizability. But it seems also to be the advantage of AMP since we can feed lots of motions to make the motion diverse while still human-like. Besides, AMP is trained in a physical simulator so we don't apply many other supervisions to make it physically plausible.
Looking forward to your reply.

**Comment by yz-cnsdqz** [comment]
Thanks for your feedback. Seems that the email reply is not posted here. 
The diversity and the generalizability in GAMMA are more w.r.t. the body shape. In physical simulation, the policy is normally (to my knowledge) tailored for a specific humanoid with pre-defined bone lengths, pd controller settings, centers of mass, etc. Definitely, how to combine our kinematics-based method with physical simulation is very interesting to explore.

**Comment by xizaoqu** [comment]
> 

Thanks for your reply.
Although I haven't tried it, I think it is feasible to map human models such as SMPL-X to simplified humanoids in the simulator and generate motions, then remap it back into SMPL-X. In this way, we also can generate various body shapes by the merit of SMPL-X. But It's true that it will sacrifice several dimensions of freedom.
